[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin=lib/openzeppelin-contracts",
    "@lop/contracts=lib/limit-order-protocol/contracts",
    "@1inch/solidity-utils=lib/solidity-utils"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
